version: '3.7'
services:
  postgres_db:
        image: postgres:latest
        restart: always
        expose:
          - "5432"
        ports:
          - "5432:5432"
        environment:
          - "POSTGRES_PASSWORD=postgres"
          - "POSTGRES_USER=postgres"
        volumes:
          - ./db-init:/docker-entrypoint-initdb.d/