// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: private.proto

package private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlantsApiClient is the client API for PlantsApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlantsApiClient interface {
	GetPlants(ctx context.Context, in *GetPlantsRequest, opts ...grpc.CallOption) (*GetPlantsResponse, error)
}

type plantsApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPlantsApiClient(cc grpc.ClientConnInterface) PlantsApiClient {
	return &plantsApiClient{cc}
}

func (c *plantsApiClient) GetPlants(ctx context.Context, in *GetPlantsRequest, opts ...grpc.CallOption) (*GetPlantsResponse, error) {
	out := new(GetPlantsResponse)
	err := c.cc.Invoke(ctx, "/go.private.plants.PlantsApi/GetPlants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlantsApiServer is the server API for PlantsApi service.
// All implementations must embed UnimplementedPlantsApiServer
// for forward compatibility
type PlantsApiServer interface {
	GetPlants(context.Context, *GetPlantsRequest) (*GetPlantsResponse, error)
	mustEmbedUnimplementedPlantsApiServer()
}

// UnimplementedPlantsApiServer must be embedded to have forward compatible implementations.
type UnimplementedPlantsApiServer struct {
}

func (UnimplementedPlantsApiServer) GetPlants(context.Context, *GetPlantsRequest) (*GetPlantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlants not implemented")
}
func (UnimplementedPlantsApiServer) mustEmbedUnimplementedPlantsApiServer() {}

// UnsafePlantsApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlantsApiServer will
// result in compilation errors.
type UnsafePlantsApiServer interface {
	mustEmbedUnimplementedPlantsApiServer()
}

func RegisterPlantsApiServer(s grpc.ServiceRegistrar, srv PlantsApiServer) {
	s.RegisterService(&PlantsApi_ServiceDesc, srv)
}

func _PlantsApi_GetPlants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsApiServer).GetPlants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.private.plants.PlantsApi/GetPlants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsApiServer).GetPlants(ctx, req.(*GetPlantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlantsApi_ServiceDesc is the grpc.ServiceDesc for PlantsApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlantsApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.private.plants.PlantsApi",
	HandlerType: (*PlantsApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlants",
			Handler:    _PlantsApi_GetPlants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "private.proto",
}
